<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"楼宇管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLouyu"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍管理",
                        "menuJump":"列表",
                        "tableName":"sushe"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿舍人员管理",
                        "menuJump":"列表",
                        "tableName":"susheRenyuan"
                    }
                ],
                "menu":"宿舍管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宿管管理",
                        "menuJump":"列表",
                        "tableName":"suguan"
                    }
                ],
                "menu":"宿管管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"访客管理",
                        "menuJump":"列表",
                        "tableName":"fangke"
                    }
                ],
                "menu":"访客管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"宿舍管理",
                        "menuJump":"列表",
                        "tableName":"sushe"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"宿舍人员管理",
                        "menuJump":"列表",
                        "tableName":"susheRenyuan"
                    }
                ],
                "menu":"宿舍管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"访客管理",
                        "menuJump":"列表",
                        "tableName":"fangke"
                    }
                ],
                "menu":"访客管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"宿管",
        "tableName":"suguan"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"宿舍管理",
                        "menuJump":"列表",
                        "tableName":"sushe"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"宿舍人员管理",
                        "menuJump":"列表",
                        "tableName":"susheRenyuan"
                    }
                ],
                "menu":"宿舍管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"访客管理",
                        "menuJump":"列表",
                        "tableName":"fangke"
                    }
                ],
                "menu":"访客管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"学生",
        "tableName":"xuesheng"
    }
];

var hasMessage = '';
